title: Pradnya Deshpande
description: Azure Cloud & DevOps Engineer

url: "https://learnwithpradnya.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: false


aux_links:
  "<strong>GitHub</strong>": https://github.com/learnwithpradnya
  "<strong>LinkedIn</strong>": https://www.linkedin.com/in/learnwithpradnya


just_the_docs:
  navigation_depth: 2
