title: Pradnya Deshpande
description: Azure Cloud & DevOps Engineer

url: "https://learnwithpradnya.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

aux_links:
  GitHub: https://github.com/learnwithpradnya
  LinkedIn: https://www.linkedin.com/in/learnwithpradnya

just_the_docs:
  navigation_depth: 2
