title: Pradnya Deshpande
description: Azure Cloud & DevOps Engineer
theme: just-the-docs

url: "https://learnwithpradnya.github.io"

aux_links:
  GitHub: https://github.com/learnwithpradnya

just_the_docs:
  navigation_depth: 2
